name: GitHub Actions Demo
run-name: ${{ github.actor }} estÃ¡ testando uma GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ O job foi acionado automaticamento pelo evento ${{ github.event_name }}."
      - run: echo "ğŸ§ Este trabalho estÃ¡ sendo executado em um servidor ${{ runner.os }} hospedado pelo GitHub!"
      - run: echo "ğŸ” O nome da branch Ã© ${{ github.ref }} e seu repositÃ³rio Ã© ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ O repositÃ³rio ${{ github.repository }} foi clonado pelo runner."
      - run: echo "ğŸ–¥ï¸ O fluxo de trabalho estÃ¡ pronto para testar seu cÃ³digo no runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ O status deste job Ã© ${{ job.status }}."
